---
- name: systemd operations
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Include systemd operations role
      ansible.builtin.include_role:
        name: systemd_operations
      tags: 
        - stop
        - start
        - restart
        - reload
