---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    omniflix:
      hosts:
        validator.omniflix.testnet.encapsulate.xyz:
    quicksilver:
      hosts:
        validator.quicksilver.testnet.encapsulate.xyz:
    celestia:
      hosts:
        validator.celestia.testnet.encapsulate.xyz:
    humans:
      hosts:
        validator.humans.testnet.encapsulate.xyz:
    ojo:
      hosts:
        validator.ojo.testnet.encapsulate.xyz:
    umee:
      hosts:
        validator.umee.testnet.encapsulate.xyz:
    c4e:
      hosts:
        validator.c4e.testnet.encapsulate.xyz:
    axelar:
      hosts:
        validator.axelar.testnet.encapsulate.xyz:
   berachain:
      hosts:
        fullnode.berachain.testnet.encapsulate.xyz:
    storyprotocol:
      hosts:
        validator.storyprotocol.testnet.encapsulate.xyz:
    supra:
      hosts:
        validator.supra.testnet.encapsulate.xyz:
        fullnode.supra.testnet.encapsulate.xyz:
