---
- name: Reload service
  ansible.builtin.systemd:
    daemon_reload: true
  when: command is defined and command == "reload"

- name: Start service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: started
    enabled: true
  when: command is defined and command == "start"

- name: Restart service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: restarted
  when: command is defined and command == "restart"

- name: Stop service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: stopped
  when: command is defined and command == "stop"
